info:
 component: Zuul Server

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 900000000

ribbon.ReadTimeout: 900000000
zuul.host.connect-timeout-millis: 900000000
zuul.host.socket-timeout-millis: 900000000

endpoints:
 restart:
  enabled: true
 shutdown:
  enabled: true
 health:
  sensitive: false

zuul:
  routes:
    gui:
      path: /**
      url: http://localhost:3000/
    backend:
      path: /api/**
      sensitiveHeaders: Cookie,Set-Cookie
      url: http://localhost:8081/
    juke:
      path: /juke/**
      url: http://msh-360.catalog.api.247e.com

logging:
  level:
    ROOT: INFO
org.springframework.web: INFO